### ISSUE TITLE
Unable to create Buckets - DataBucketName and ModelBucketName

### ISSUE THREAD

**Issue by melpais** [aws-samples/amazon-sagemaker-secure-mlops#2]
When launched in Sydney region, the SC is uable to create bucket as some one else created bucket with that name.

https://github.com/aws-samples/amazon-sagemaker-secure-mlops/blob/d3139d79a073583d1aab38963275c426abb95ee9/cfn_templates/env-main.yaml#L1136
https://github.com/aws-samples/amazon-sagemaker-secure-mlops/blob/d3139d79a073583d1aab38963275c426abb95ee9/cfn_templates/env-main.yaml#L1142

**Comment by yevgeniyilyin** [comment]
Documentation updated to reflect this.
